name: Download and Combine Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 0'

permissions:
  contents: write

jobs:
  build_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Release Manager
        id: release-manager
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: ./scripts/manage_releases.sh

      - name: Configure Release Files
        if: steps.release-manager.outputs.updates_found == 'true'
        run: ./scripts/configure_release.sh

      - name: Create Archive
        if: steps.release-manager.outputs.updates_found == 'true'
        run: |
          cd release
          zip -r ../PYXIS_SwitchAIO.zip ./*

      - name: Commit and Push
        if: steps.release-manager.outputs.updates_found == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifest.json
          git commit -m "Build ${{ steps.release-manager.outputs.tag }} - ${{ steps.release-manager.outputs.date }}"
          git push

      - name: Create Release
        if: steps.release-manager.outputs.updates_found == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ steps.release-manager.outputs.tag }}
          release_name: Build ${{ steps.release-manager.outputs.tag }} - ${{ steps.release-manager.outputs.date }}
          body: ${{ env.RELEASE_BODY }}
          file: PYXIS_SwitchAIO.zip

  prune_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 7
